### ISSUE TITLE
Errors in Log.

### ISSUE THREAD

**Issue by InflamedSebi** [MrBrikster/chatty#13]
Getting errors whenever someone types ... any clue?

`[15:50:23] [Async Chat Thread - #0/INFO]: Calli: yee
[15:50:59] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.1
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
at net.minecraft.server.v1_13_R1.PlayerConnection.chat(PlayerConnection.java:1556) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1494) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
at net.minecraft.server.v1_13_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IllegalStateException: Asynchronous command dispatch!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:691) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:576) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
at ru.mrbrikster.chatty.fanciful.FancyMessage.send(FancyMessage.java:472) ~[?:?]
at ru.mrbrikster.chatty.fanciful.FancyMessage.send(FancyMessage.java:496) ~[?:?]
at ru.mrbrikster.chatty.json.FormattedMessage.send(FormattedMessage.java:23) ~[?:?]
at ru.mrbrikster.chatty.listeners.ChatListener.onJsonMessage(ChatListener.java:266) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
... 11 more`

**Comment by MrBrikster** [comment]
Thanks, fixed!
